### PR TITLE
Drop support for Puppet 4, Debian 7, and CentOS 6

### PR DESCRIPTION
**Pull request by wyardley**
#### Pull Request (PR) description
- Drop support for Puppet 4
- Drop support for Debian 7
- Drop support for CentOS 6

#### This Pull Request (PR) fixes the following issues
Closes: #2

### CODE REVIEW

**Review by nmaludy — APPROVED** [review]

**Comment by wyardley** [comment]
@nmaludy any ideas about the failures mentioned in #2? Maybe later versions of Debian and most versions of Ubuntu already have a conflicting package available in their default repo?
 
```
  Unpacking erlang-typer (1:23.2.1-1) ...
  dpkg: error processing archive /tmp/apt-dpkg-install-1yZb5x/19-erlang-typer_1%3a23.2.1-1_amd64.deb (--unpack):
   trying to overwrite '/usr/lib/erlang/bin/typer', which is also in package erlang-base 1:23.2.1-1
```

**Comment by nmaludy** [comment]
@wyardley looks like `erlang-solutions` has some apt stuff going on that doesn't properly resolve its dependencies: https://github.com/voxpupuli/puppet-erlang/pull/3/checks?check_run_id=1623109601#step:5:1104

**Comment by nmaludy** [comment]
@wyardley i'm not an `apt` wizard, is there a way to tell `apt` and specifically the `package` resource to auto-install dependent packages?

**Comment by kenyon** [comment]
> @wyardley i'm not an `apt` wizard, is there a way to tell `apt` and specifically the `package` resource to auto-install dependent packages?

@nmaludy installing dependencies is the default behavior. Something else is wrong here.

**Comment by wyardley** [comment]
On my local run of Debian 9, it seems like it’s the ensure absent that was failing. With the new modulesync changes, having some trouble working with the acceptance tests locally, though

**Comment by ekohl** [comment]
> With the new modulesync changes, having some trouble working with the acceptance tests locally, though

What is the problem?

**Comment by wyardley** [comment]
> > With the new modulesync changes, having some trouble working with the acceptance tests locally, though

> What is the problem?

`bundle exec rake beaker:sets` doesn't return anything (for this module, anyway), and `bundle exec rake beaker:ssh` doesn't work even if I set `BEAKER_setfile`. `bundle exec rake beaker` also fails for me (probably because of missing `spec/acceptance/nodesets`. I realize it builds these nodesets in CI, but not sure whether they're supposed to exist in this module or not, or whether it's supposed to be built dynamically here too?

I can do something like
```
BEAKER_destroy=no PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker bundle exec rake beaker
```

but I can't then do anything like
```
$ bundle exec beaker:ssh
```
or
```
$ BEAKER_setfile=debian9-64 bundle exec beaker:ssh
```

**Comment by ekohl** [comment]
> `BEAKER_destroy=no PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker bundle exec rake beaker`

It should be sufficient to use:

`BEAKER_destroy=no BEAKER_setfile=debian9-64 bundle exec rake beaker`

This is because we do have some defaults built in:

https://github.com/voxpupuli/voxpupuli-acceptance/blob/master/lib/voxpupuli/acceptance/spec_helper_acceptance.rb#L29-L32

I did that because I was getting sick of writing that all the time.



> but I can't then do anything like

I never got `beaker:ssh` to work with docker. Looking at [the code](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/tasks/beaker.rb) it can only work with vagrant. However, only with `BEAKER_set` and not `BEAKER_setfile`.

I've been thinking of dropping that part of puppetlabs_spec_helper and implement it ourselves or in Beaker directly.

For the short term I'd recommend to either use the vagrant(_libvirt) hypervisor or directly attach the docker console with `docker exec -it -u root $CONTAINER_ID bash`.

**Comment by wyardley** [comment]
> It should be sufficient to use:

> BEAKER_destroy=no BEAKER_setfile=debian9-64 bundle exec rake beaker

Yeah, that works. Is there a rake task to print the available options, though? If they're going to be dynamic, it would be nice to be able to at a minimum get the list of available integration tests to run, and (even better), be able to run them via rake task (e.g., `rake beaker:debian-8-x64`, as would show up in rake tasks if the acceptance tests were listed explicitly).

> For the short term I'd recommend to either use the vagrant(_libvirt) hypervisor or directly attach the docker console with docker exec -it -u root $CONTAINER_ID bash.

Yeah, that's what I've done in the past with Docker as well. I was a little confused by Puppet not being in `$PATH`, but it seems to work

With this Debian 9 error, anyway
```
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 erlang : Depends: erlang-typer but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
If I apply the manifest going between present and absent it _seems_ mostly to be happy enough, so not sure if this is just a case of the acceptance test getting in a wacky state from switching repos in the various tests, or if there's actually an issue.

**Comment by wyardley** [comment]
```
Preparing to unpack .../erlang-typer_1%3a23.2.1-1_amd64.deb ...
Unpacking erlang-typer (1:23.2.1-1) ...
dpkg: error processing archive /var/cache/apt/archives/erlang-typer_1%3a23.2.1-1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/erlang/bin/typer', which is also in package erlang-base 1:23.2.1-1
Errors were encountered while processing:
 /var/cache/apt/archives/erlang-typer_1%3a23.2.1-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Beginning to think this is an actual issue with the erlang-solutions packages (with `erlang-typer` being required, but also including a file that's also included in the erlang package, or something along those lines?)

**Comment by wyardley** [comment]
```
root@ubuntu1604-64-1:/tmp# dpkg -s erlang
Package: erlang
Status: install ok unpacked
Priority: optional
Section: interpreters
Installed-Size: 58
Maintainer: Debian Erlang Packagers <pkg-erlang-devel@lists.alioth.debian.org>
Architecture: all
Version: 1:23.2.1-1
```

Even though the version matches, I think this is actually the regular Debian erlang package, not the erlang-solutions package, hence the conflicts. Not sure what the right behavior for the module is in this scenario. If it were me, I'd tend to use the vendor's available version if a reasonable version is already available, but that would make this module somewhat more complicated and also less consistent, so 🤷

**Comment by wyardley** [comment]
I don't know that we'd want to do it in an integration test, but it seems that setting a value like `100` for `package_apt_pin` may fix it (by forcing it to prefer this version).

**Comment by ekohl** [comment]
> Yeah, that's what I've done in the past with Docker as well. I was a little confused by Puppet not being in `$PATH`, but it seems to work

I guess bash doesn't execute `/etc/profile.d/puppet-agent.sh` then. You can source it to get it in `$PATH`.

**Comment by wyardley** [comment]
I'm thinking either way, may be best to merge this one on red (as 3 atomic commits), and then merge any additional changes needed in separate PRs?

**Comment by kenyon** [comment]
I haven't tried to run these tests locally, but I think the acceptance test needs to uninstall the previous package and apt source repo configuration before trying to install the same package from a different source. Otherwise you have wrong package metadata for the currently-installed package when the source changes. So doing basically this "removing package and repo source" test between each installation test would probably work better: https://github.com/voxpupuli/puppet-erlang/blob/master/spec/acceptance/init_spec.rb#L189

That's what I had to do with the nodejs module: https://github.com/voxpupuli/puppet-nodejs/blob/master/spec/acceptance/class_spec.rb#L83

It would be nice if beaker or litmus could run certain tests on separate machines/containers, thus avoiding this kind of package management work in the tests, but it appears that there's no built-in way to do that.

**Comment by wyardley** [comment]
That’s what I thought, but there’s an ensure absent at the end, and I’m also pretty sure it’s the Debian one, not the bintray one, that seems to be causing the issue here.

**Comment by wyardley** [comment]
```diff
diff --git a/data/family/Debian.yaml b/data/family/Debian.yaml
index 110c059..b8daa8a 100644
--- a/data/family/Debian.yaml
+++ b/data/family/Debian.yaml
@@ -1,2 +1,3 @@
 ---
 erlang::repo_source: 'bintray'
+erlang::package_apt_pin: 200
```

Seems to pass for me with this, however, I'm not sure if this is a safe change to make in defaults.

**Pull request merged**
